languages:
  es:
    - "8M"
    - "marcha 8M"
    - "movilización 8M"
    - "convocatoria 8M"
    - "paro feminista"
    - "día internacional de la mujer"
    - "marcha feminista"
    - "manifestación 8M"
  en:
    - "Women's March"
    - "International Women's Day march"
    - "8 March protest"
    - "feminist march"
    - "feminist rally"
    - "IWD event"
  pt:
    - "8M"
    - "Dia Internacional da Mulher"
    - "ato 8M"
    - "mobilização feminista"
    - "marcha feminista"
  fr:
    - "8 mars manifestation"
    - "journée internationale des droits des femmes"
    - "manifestation féministe"
    - "marche 8 mars"

event_terms:
  - "marcha"
  - "manifestación"
  - "concentración"
  - "plantón"
  - "taller"
  - "conversatorio"
  - "foro"
  - "vigilia"
  - "rally"
  - "march"
  - "rally"
  - "protest"
  - "event"
  - "workshop"
  - "manifestation"
  - "marche"
