seeds:
  - https://assemblea8m.cat
  - https://www.grevefeministe.fr
  - https://8mitalia.wordpress.com
  - https://frauenstreik.org
  - https://www.marchamulheres.org
  - https://www.womensmarch.com
  - https://feministfrequency.com
  - https://www.niunamenos.org.ar
  - https://www.femmes-solidaires.org
  - https://www.nonunadimeno.it
  - https://www.frauen-gegen-gewalt.de
  - https://www.marchamulheres.pt
  - https://www.ultraviolet.org
  - https://www.codepink.org
  - https://www.feministas.org
  - https://www.feminist.com
  - https://www.collectif-feministe-ruptures.org
  - https://www.womenonwaves.org
  - https://www.feminicidio.net
  - https://www.chayn.co
  - https://www.mujeresenred.net
  - https://www.mujerescreando.org

feminist_media:
  - https://www.pikaramagazine.com
  - https://www.latfem.org
  - https://www.the19thnews.org
  - https://www.msmagazine.com
  - https://www.axellemag.be
  - https://www.causette.fr
  - https://www.ingenere.it
  - https://www.missy-magazin.de
  - https://www.revistaazmina.com.br
  - https://www.generonumero.com
  - https://www.malvestida.com
  - https://www.volcanicas.com
  - https://www.opendemocracy.net/en/5050

orgs:
  - https://www.unwomen.org
  - https://www.awid.org
  - https://www.cladem.org
  - https://www.globalfundforwomen.org
  - https://www.calala.org
  - https://www.equalitynow.org
  - https://www.madre.org
  - https://www.apwld.org
  - https://www.womankind.org.uk
  - https://www.planning-familial.org
  - https://www.themis.org.br
  - https://www.centerforreproductiverights.org
  - https://www.womenforwomen.org
  - https://www.fondoaccionurgente.org.uy
  - https://www.mama-cash.org

networks:
  - https://www.marchemondiale.org
  - https://www.womenlobby.org
  - https://www.gnwp.org
  - https://www.wiego.org
  - https://www.wave-network.org
  - https://www.menengage.org
  - https://www.wlb.org
